spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: main_access
            client-secret: aarnV3ngWtnpYKv1EQ4IIx2ITijAiRpc
            authorization-grant-type: authorization_code
            redirect-uri: ${HOST_URL}/p2proto/login/oauth2/code/{registrationId}
            scope: openid, profile, email
            realm: platform
        provider:
          keycloak:
            authorization-uri: ${HOST_URL}/realms/platform/protocol/openid-connect/auth
            token-uri: http://host.docker.internal/realms/platform/protocol/openid-connect/token
            user-info-uri: http://host.docker.internal/realms/platform/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: http://host.docker.internal/realms/platform/protocol/openid-connect/certs
            issuer-uri: ${HOST_URL}/realms/platform
            logout-uri: ${HOST_URL}/realms/platform/protocol/openid-connect/logout
            post-logout-redirect-uri: ${HOST_URL}/p2proto/
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /p2proto
