services:
  p2proto:
    image: p2proto:latest
    container_name: p2proto
    expose:
      - "8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend
    environment:
      - HOST_URL=${HOST_URL:-http://localhost}  # Use .env value or default to localhost

  keycloak:
    image: keycloak_p:latest
    ports:
      - 8081:8080
    #      - 5005:5005
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/platform?currentSchema=keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: qwerty
    #      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Necessary on Linux
    command:
      - start-dev
      - --verbose
      - --hostname-url=http://localhost:8081
      - --import-realm
      - --file=/opt/keycloak/data/import/realm-export.json
      - --spi-import-export-strategy=IGNORE_EXISTING
    networks:
      - backend

  nginx:
    image: nginx_p:latest
    container_name: nginx
    depends_on:
      - p2proto
      - keycloak
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
